import { useEffect, useState } from 'react';
import { ArrowUpRight, BookOpen, Clock3, Code2, MessageSquareText, UsersRound } from 'lucide-react';
import { Link } from 'react-router-dom';
import Card from '../components/ui/Card';
import Skeleton from '../components/ui/Skeleton';
import { getConversations, getKnowledge, getSettings } from '../lib/genmb';
import type { Conversation, KnowledgeItem, Settings } from '../types';
import { formatDate } from '../lib/utils';

export default function OverviewPage() {
  const [knowledge, setKnowledge] = useState<KnowledgeItem[]>([]);
  const [conversations, setConversations] = useState<Conversation[]>([]);
  const [settings, setSettings] = useState<Settings | null>(null);
  const [error, setError] = useState('');
  const load = async () => { setError(''); try { const [items, logs, config] = await Promise.all([getKnowledge(), getConversations(), getSettings()]); setKnowledge(items); setConversations(logs); setSettings(config); } catch (err) { setError(err instanceof Error ? err.message : String(err)); } };
  useEffect(() => { document.title = 'ReplyHarbor AI Dashboard'; document.querySelector('meta[name="description"]')?.setAttribute('content', 'Monitor your AI customer assistant, knowledge base, leads, and customer conversation handoffs.'); void load(); }, []);
  const leads = new Set(conversations.map((item) => item.visitorEmail)).size;
  const needsFollowUp = conversations.filter((item) => item.status === 'Needs follow-up').length;
  const metrics = [{ label: 'Knowledge answers', value: knowledge.length, icon: BookOpen }, { label: 'Conversations', value: conversations.length, icon: MessageSquareText }, { label: 'Captured leads', value: leads, icon: UsersRound }, { label: 'Need follow-up', value: needsFollowUp, icon: Clock3 }];

  return <div className="space-y-8">
    <section className="grid gap-6 rounded-xl border border-border bg-card p-6 shadow-sm lg:grid-cols-[1.4fr_0.6fr] lg:p-8"><div className="space-y-6"><div className="space-y-3"><p className="text-sm font-medium text-primary">Customer conversations, kept human</p><h1 className="max-w-xl text-3xl font-bold tracking-tight sm:text-4xl">Your business knowledge, ready for every question.</h1><p className="max-w-prose text-base text-muted-foreground">ReplyHarbor answers routine questions, captures contact details, and sends a thoughtful handoff when a customer needs your team.</p></div><div className="flex flex-wrap gap-3"><Link to="/knowledge" className="inline-flex min-h-10 items-center gap-2 rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow-sm transition hover:-translate-y-0.5 hover:shadow-md focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2"><BookOpen className="size-4" />Manage knowledge</Link><Link to="/widget" className="inline-flex min-h-10 items-center gap-2 rounded-md border border-border bg-secondary px-4 py-2 text-sm font-medium text-secondary-foreground transition hover:bg-accent focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2"><Code2 className="size-4" />Preview widget</Link></div></div><div className="rounded-lg border border-border bg-muted p-6"><p className="text-sm font-medium text-muted-foreground">Assistant status</p><p className="mt-4 text-2xl font-semibold tracking-tight">Ready to help</p><p className="mt-2 text-sm text-muted-foreground">{settings?.businessName ?? 'Your business'} is set to collect leads and notify your team for unanswered questions.</p></div></section>
    {error ? <section className="rounded-lg border border-destructive/40 bg-card p-6"><p className="font-medium text-destructive">We could not load your workspace.</p><p className="mt-1 text-sm text-muted-foreground">{error}</p><button onClick={() => void load()} className="mt-4 rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2">Try again</button></section> : <>
      <section aria-labelledby="metrics-heading" className="space-y-6"><div><p className="text-sm font-medium text-muted-foreground">At a glance</p><h2 id="metrics-heading" className="text-2xl font-semibold tracking-tight">Today’s support pulse</h2></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map((metric) => { const Icon = metric.icon; return <Card key={metric.label} className="p-5"><div className="flex items-start justify-between"><p className="text-sm text-muted-foreground">{metric.label}</p><Icon className="size-5 text-primary" /></div><div className="mt-4 text-3xl font-semibold tracking-tight">{knowledge.length || conversations.length || settings ? metric.value : <Skeleton className="h-9 w-16" />}</div></Card>; })}</div></section>
      <section className="grid gap-6 lg:grid-cols-[1.2fr_0.8fr]"><Card><div className="flex items-center justify-between gap-4"><div><p className="text-sm font-medium text-muted-foreground">Conversation log</p><h2 className="text-xl font-semibold tracking-tight">Latest customer questions</h2></div><Link to="/conversations" className="inline-flex items-center gap-1 text-sm font-medium text-primary hover:underline">View all <ArrowUpRight className="size-4" /></Link></div><div className="mt-6 overflow-x-auto"><table className="w-full min-w-[520px] text-left text-sm"><thead className="sticky top-0 bg-muted text-muted-foreground"><tr><th className="px-4 py-3 font-medium">Customer</th><th className="px-4 py-3 font-medium">Status</th><th className="px-4 py-3 text-right font-medium">Last message</th></tr></thead><tbody>{conversations.slice(0, 4).map((item) => <tr key={item.id} className="border-t border-border hover:bg-muted/50"><td className="px-4 py-3"><p className="font-medium">{item.visitorName}</p><p className="text-xs text-muted-foreground">{item.visitorEmail}</p></td><td className="px-4 py-3"><span className={item.status === 'Resolved' ? 'rounded-full bg-[hsl(var(--success)/0.12)] px-2 py-1 text-xs font-medium text-success' : 'rounded-full bg-[hsl(var(--warning)/0.12)] px-2 py-1 text-xs font-medium text-warning'}>{item.status}</span></td><td className="px-4 py-3 text-right text-muted-foreground">{formatDate(item.updatedAt)}</td></tr>)}</tbody></table></div></Card><Card><p className="text-sm font-medium text-muted-foreground">Embed it anywhere</p><h2 className="mt-2 text-xl font-semibold tracking-tight">A friendly front door for support.</h2><p className="mt-3 text-sm text-muted-foreground">Give visitors answers in the flow of browsing, then make it easy for your team to step in.</p><Link to="/settings" className="mt-6 inline-flex items-center gap-2 text-sm font-medium text-primary hover:underline">Configure channels <ArrowUpRight className="size-4" /></Link></Card></section>
    </>}
  </div>;
}
